-- (B-A)^2 --  POWER(MAX(LAT_N)-MIN(LAT_N),2)
-- (D-C)^2 --  POWER(MAX(LONG_W)-MIN(LONG_W),2)
-- EUCLIDEAN DISTANCE -- SQRT(POWER(MAX(LAT_N)-MIN(LAT_N),2)+POWER(MAX(LONG_W)-MIN(LONG_W),2))

SELECT  ROUND(SQRT(POWER(MAX(LAT_N)-MIN(LAT_N),2)+POWER(MAX(LONG_W)-MIN(LONG_W),2)),4)
FROM STATION
